name = "my-first-worker"
type = "webpack"
account_id = "d37ab906812cbc49bfff95e41dd1f736"
workers_dev = false
zone_id = "b9bf055168903c1cd533603c2bf026c1"
routes = [
  "https://www.rankia.mx/blog/*",
  "https://www.rankia.mx/foros/*"
]
